# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Epinio < Formula
  desc "CLI for Epinio, the Application Development Engine for Kubernetes"
  homepage "https://epinio.io/"
  version "1.10.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/epinio/epinio/releases/download/v1.10.0/epinio-darwin-arm64"
      sha256 "82a3007137d262c76a4b76e097d36ae6f9946484c07691317dd1eb3c24ca7d6d"

      def install
        bin.install "epinio-darwin-arm64" => "epinio"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/epinio/epinio/releases/download/v1.10.0/epinio-darwin-x86_64"
      sha256 "3d319cca4bee79296b3714816985f42a1ddcaf258ec825e303b2ba024e353474"

      def install
        bin.install "epinio-darwin-x86_64" => "epinio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/epinio/epinio/releases/download/v1.10.0/epinio-linux-arm64"
      sha256 "4df0e84e97311368f647f6084e55d84068f3a6fef969e13c5ce2d42bb24548d8"

      def install
        bin.install "epinio-linux-arm64" => "epinio"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/epinio/epinio/releases/download/v1.10.0/epinio-linux-x86_64"
      sha256 "33aedf0a932ca083f3997b5d47d39afb192d3e712564a3bbcbb6812130b26799"

      def install
        bin.install "epinio-linux-x86_64" => "epinio"
      end
    end
  end

  test do
    output = shell_output("#{bin}/epinio version 2>&1")
    assert_match "Epinio Version: #{version}", output
    output = shell_output("#{bin}/epinio settings update-ca 2>&1")
    assert_match "failed to get kube config", output
    assert_match "no configuration has been provided", output
  end
end
